version: '2'

services:
  app:
    build: .
    command: bash -c "cd /app && dotnet restore && dotnet watch run --server.urls http://*:5000"
    ports:
      - '80:5000'
    volumes:
      - '.:/app'
